on: push

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: First step
        run: echo "Hello from a job"
      - name: Run go program
        run: go run ./main.go