on:
  pull_request:
    types: [opened]
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: First step
        run: echo "Hello from a job on a ${{ github.event.number }}"

      - name: Bump the image
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          ./bump.sh ${{ github.event.number }}
          git config --global user.name "CI"
          git config --global user.email "ci@void"
          git status
          git add values.yaml
          git commit -m "bump the image tag"
      - name: Push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push